[versions]
appcompat = "1.7.0"
material = "1.12.0"
constraintLayout = "2.1.4"
androidxFragment = "1.8.0"
junit = "4.13.2"
androidxTestJunit = "1.1.5"
espresso = "3.5.1"
legacy = "1.0.0"
core = "1.13.1"
coroutines = "1.7.3"
retrofit = "2.9.0"
navigation = "2.7.7"
glide = "4.15.1"
hilt = "2.49"
jetbrainsPlugin = "1.7.20"
agp = "8.3.2"
minSdk = "22"
targetSdk = "34"
androidxRoom = "2.6.1"
timber = "5.0.1"
truth = "1.1.4"
testRunner = "1.5.2"
kotlin = "1.9.0"
androidxArchCore = "2.2.0"
androidTestJunit = "1.1.5"
org-jetbrains-kotlin-jvm = "1.9.0"
annotationJvm = "1.8.0"
coreKtx = "1.13.1"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
lifecycleRuntimeKtx = "2.8.2"
activityCompose = "1.9.0"
composeBom = "2024.06.00"
okHttp = "5.0.0-alpha.11"
hiltAndroidVersion = "2.49"
hiltPlugin = "2.49"
navigationCompose = "2.7.7"
androidxHilt = "1.2.0"
androidxHiltCompiler = "1.2.0"
flowLayout = "0.17.0"
coil="2.6.0"



[libraries]
agp = { module = "com.android.tools.build:gradle", version.ref = "agp" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }

appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
material = { module = "com.google.android.material:material", version.ref = "material" }
constraintLayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintLayout" }# necessario?
legacy = { module = "androidx.legacy:legacy-support-v4", version.ref = "legacy" }#necessario?

androidx-fragment = { module = "androidx.fragment:fragment-ktx", version.ref = "androidxFragment" }
androidx-espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }

coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }

navigation-fragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
navigation-ui = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }
navigation-features = { module = "androidx.navigation:navigation-dynamic-features-fragment", version.ref = "navigation" }
navigation-safeargs = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "navigation" }

glide-core = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glide-compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }

hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
hilt-plugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }

androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "androidxRoom" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "androidxRoom" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidxRoom" }

timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }

androidx-hilt-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "androidxHiltCompiler" }
androidx-hilt-navigation = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "androidxHilt" }

retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-converter = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }
retrofit-okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okHttp" }
retrofit-logging = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okHttp" }

dagger-hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hiltAndroidVersion" }
dagger-hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hiltAndroidVersion" }

flowLayout = { group = "com.google.accompanist", name = "accompanist-flowlayout", version.ref = "flowLayout" }
coil ={group="io.coil-kt", name="coil-compose", version.ref="coil"}
#unit test
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
room-testing = { module = "androidx.room:room-testing", version.ref = "androidxRoom" }
junitTest = { module = "junit:junit", version.ref = "junit" }
test-runner = { module = "androidx.test:runner", version.ref = "testRunner" }
androidx-arch-core = { module = "androidx.arch.core:core-testing", version.ref = "androidxArchCore" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }
junitAndroid = { module = "androidx.test.ext:junit", version.ref = "androidTestJunit" }
androidx-annotation-jvm = { group = "androidx.annotation", name = "annotation-jvm", version.ref = "annotationJvm" }


[bundles]
coroutines = ["coroutines.core", "coroutines.android"]
retrofit = ["retrofit", "retrofit-converter", "retrofit-okhttp", "retrofit-logging"]
navigation = ["navigation.fragment", "navigation.ui", "navigation-features"]
androidX = ["androidx-core-ktx", "appcompat", "constraintLayout"]
room = ["androidx-room-runtime", "androidx-room-ktx"]
androidTest = ["junitAndroid", "androidx-espresso", "coroutines-test", "androidx-arch-core"]
dagger = ["dagger-hilt-android", "androidx-hilt-navigation"]
dagger-compiler = ["dagger-hilt-android-compiler", "androidx-hilt-compiler"]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
hilt-plugin = { id = "com.google.dagger.hilt.android", version.ref = "hiltPlugin" }
safeargs = { id = "androidx.navigation.safeargs.kotlin", version.ref = "navigation" }
org-jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "org-jetbrains-kotlin-jvm" }

