name: 🚀 Feature Request
description: Suggest an idea for this project
title: "<title>"
labels: ["enhancement"]
assignees:
  - Indisparte
body:
  - type: checkboxes
    attributes:
     label: 
     options:
      - label: I checked if there is a project named like this repo. If it exists, I proceeded to assign this issue to that project 
        required: true
  - type: textarea
    attributes:
      label: Is your feature request related to a problem? Please describe.
      placeholder: |
        A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe alternatives you have considered.
      placeholder: |
        A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional Context
      placeholder: |
       Add any other context or screenshots about the feature request here.
    validations:
      required: false
 
