package com.example.cinemates.model.entities

class TvShow(
    backdrop_path: String,
    val created_by: List<CreatedBy>,
    val episode_run_time: List<Int>,
    val first_air_date: String,
    genres: List<Genre>,
    homepage: String,
    id: Int,
    val in_production: Boolean,
    val languages: List<String>,
    val last_air_date: String,
    val last_episode_to_air: LastEpisodeToAir,
    val name: String,
    val networks: List<Network>,
    val next_episode_to_air: Any,
    val number_of_episodes: Int,
    val number_of_seasons: Int,
    val origin_country: List<String>,
    original_language: String,
    val original_name: String,
    overview: String,
    popularity: Double,
    poster_path: String,
    production_companies: List<ProductionCompany>,
    production_countries: List<ProductionCountry>,
    val seasons: List<Season>,
    spoken_languages: List<SpokenLanguage>,
    status: String,
    val tagline: String,
    val type: String,
    vote_average: Double,
    vote_count: Int
) : Media(
    backdrop_path,
    genres,
    homepage,
    id,
    original_language,
    overview,
    popularity,
    poster_path,
    production_companies,
    production_countries,
    spoken_languages,
    status,
    vote_average
)